### ISSUE TITLE
Help!!!!!!!!!

### ISSUE THREAD

**Issue by pixixiaonaogou** [zhiaozhou/Vehicle_Count_Deep_Learning#1]
excuse me , it is very useful for my project that the code and paper you share, and then , i cant find the the file of train_image_classfier.py .So ,can you help me to share your code or tell me where is it ? 
Thanks for you share

**Comment by zhiaozhou** [comment]
Hi, I just made a new commit. You should now be able to find it in the slim folder.

**Comment by pixixiaonaogou** [comment]
Wow~,Thank you for your generous~.
------------------ 原始邮件 ------------------
发件人: "Zhiao Zhou"<notifications@github.com>;
发送时间: 2018年6月17日(星期天) 上午10:57
收件人: "zhiaozhou/Vehicle_Count_Deep_Learning"<Vehicle_Count_Deep_Learning@noreply.github.com>;
抄送: "老三"<3487944589@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zhiaozhou/Vehicle_Count_Deep_Learning] Help!!!!!!!!! (#1)




Closed #1.

**Comment by pixixiaonaogou** [comment]
Thanks for your generous, and I am a college student from China and I have tried to search for Annotated Driving Dataset(COWC if finded by me ) ,but I can not find it ,Can you give me a URL to download it , I want to expand my dataset to improve my precision with the data.

**Comment by zhiaozhou** [comment]
@pixixiaonaogou 我用的是UDACITY提供的训练数据，https://github.com/udacity/self-driving-car/tree/master/annotations  。不过如果你需要更大的样本的话我建议你自己贴标签。
